#
# http://xmeblog.blogspot.hu/2013/06/ansible-dynamicaly-update-etchosts.html
#
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:
  - name: Name master
    lineinfile: dest=/etc/hosts
                regexp='^(.*)({{master}}.{{domains.system}})$'
                line='\1\2 master'
                backup=yes
                backrefs=yes
    tags:
      - hosts

  - name: Name backup
    lineinfile: dest=/etc/hosts
                regexp='^(.*)({{backup}}.{{domains.system}})$'
                line='\1\2 backup'
                backup=yes
                backrefs=yes
    tags:
      - hosts
