#
# http://xmeblog.blogspot.hu/2013/06/ansible-dynamicaly-update-etchosts.html
#
---
- hosts: all

  vars_files:
    - networks.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
  - name: Name master
    lineinfile: dest=/etc/hosts
                regexp='.*{{master}}.*'
                line='${hostvars.${master}.ansible_eth0.ipv4.address} ${master} ${master}.${domains.system} master'
                backup=yes

  - name: Name backup
    lineinfile: dest=/etc/hosts
                regexp='.*{{backup}}.*'
                line='${hostvars.${backup}.ansible_eth0.ipv4.address} ${backup} ${backup}.${domains.system} backup'
                backup=yes
