#
# http://myitnotes.info/doku.php?id=en:jobs:lustrefs
#
# TODO: move network to lustre
# hostvars for problem???
---
- hosts: all

  vars_files:
    - networks.yml
    - vars/lustre.yml

  # TODO: better bonding detect
  vars:
    nobond: true
    format: false

  tasks:

### NETWORK
# /etc/network is installed
    - name: Enable LNET modul
      template: src=templates/etc/modprobe.d/lustre.conf.j2
                dest=/etc/modprobe.d/lustre.conf
                backup=yes
      tags:
        - module


### FIREWALL
    - name: Install ipset tables
      template: src=templates/etc/ipset.d/{{item}}.j2
                dest=/etc/ipset.d/{{item}}
                owner=root
                group=root
                mode=0755
      with_items:
        - storage.sh
      tags:
        - firewall
        - ipset
      notify:
        - Restart ipset

    - name: Enable storage firewall
      lineinfile: dest=/etc/shorewall/interfaces
                  regexp="^sys {{paths[interfaces.storage]}}"
                  line="sys {{paths[interfaces.storage]}}"
                  insertbefore='^#LAST'
                  backup=yes
      notify:
        - Restart shorewall
      tags:
        - firewall

    - name: Install firewall rules
      template: src=templates/etc/shorewall/rules.d/storage.j2
                dest=/etc/shorewall/rules.d/storage
                owner=root
                group=root
                mode=0640
      tags:
        - firewall
      notify:
      - Restart shorewall


### DISKS
    - name: Create lustre VG
      lvg: vg={{lustre.vg_root}}
           pvs={{lustre.vg_pvs}}
           pesize={{lustre.vg_size}}
      tags:
        - vg

    # ansbile bug
    - name: Create lustre LV
      lvol: vg={{lustre.vg_root}}
            lv={{lustre.lv_data}}
            size={{lustre.lv_size}}
      ignore_errors: yes
      tags:
        - partition
        - lvm

### MASTER NODE
    # format MGS/MDT master node
    # mkfs.lustre --fsname=FS --mgs --mdt --index=0 /dev/md1 (/dev/md1 is software RAID1)
    # mkdir /mdt
    # mount -t lustre /dev/md1 /mdt
    # echo ”/dev/md1 /mdt lustre defaults,_netdev 0 0” » /etc/fstab
    # fails
    # - name: Format MGS/MDT partition
    #   filesystem: fstype=lustre
    #               dev=/dev/{{lustre.vg_root}}/{{lustre.lv_data}}
    #               opts="--fsname={{lustre.fsname}} --reformat --mdt --mgs"
    #               force=yes
    #   when: inventory_hostname == master and format
    #   tags:
    #     - fs
    - name: Format MGS/MDT partition
      shell: '/usr/sbin/mkfs.lustre --reformat --fsname={{lustre.fsname}} --mdt --mgs /dev/{{lustre.vg_root}}/{{lustre.lv_data}}'
      when: inventory_hostname == master and format
      tags:
        - fs


    - name: Create MDT directory
      file: path={{lustre.mdt}}
            state=directory
      when: inventory_hostname == master
      tags:
        - directories
        - fs

    - name: Mount MDT partition
      mount: name={{lustre.mdt}}
             src=/dev/{{lustre.vg_root}}/{{lustre.lv_data}}
             fstype=lustre
             opts='defaults,_netdev'
             state=mounted
      when: inventory_hostname == master
      tags:
        - fs

### DATA NODES

    # format OSS/OST nodes

  handlers:
    - name: Restart ipset
      service: name=ipset
               state=reloaded

    - name: Restart shorewall
      service: name=shorewall
               state=restarted
