
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/${inventory_hostname}.yml

  tasks:

### FIREWALL
    - name: Install ipset tables
      template: src=templates/etc/ipset.d/{{item}}.j2
                dest=/etc/ipset.d/{{item}}
                owner=root
                group=root
                mode=0755
      with_items:
        - storage.sh
      tags:
        - ipset
      notify:
        - Restart ipset

    - name: Enable storage firewall
      lineinfile: dest=/etc/shorewall/interfaces
                  regexp="^sys {{paths[interfaces.storage]}}"
                  line="sys {{paths[interfaces.storage]}}"
                  insertbefore='^#LAST'
                  backup=yes
      notify:
        - Restart shorewall
      tags:
        - interface

    - name: Install firewall rules
      template: src=templates/etc/shorewall/rules.d/storage.j2
                dest=/etc/shorewall/rules.d/storage
                owner=root
                group=root
                mode=0640
      tags:
        - rules
      notify:
      - Restart shorewall


  handlers:
    - name: Restart ipset
      service: name=ipset
               state=reloaded

    - name: Restart shorewall
      service: name=shorewall
               state=restarted
