# TODO: better roles in ansible
---
- include: roles/database/sql.yml

- hosts: all
  tasks:
    - name: Database state done
      lineinfile: dest=/etc/ANSIBLE_STATE
                  regexp="^database"
                  line=database
                  state=present
                  create=yes
      tags:
        - state
