# TODO: better roles in ansible
#
# ANSIBLE_HOSTS=core flock play @@core mysql --extra-vars='master=core'
#
---
- include: roles/database/mysql.yml

- hosts: all
  tasks:
    - name: Database state done
      lineinfile: dest=/etc/ANSIBLE_STATE
                  regexp="^database"
                  line=database
                  state=present
                  create=yes
      tags:
        - state
