# TODO: better roles in ansible
---
- include: roles/secure/basic.yml

- hosts: all
  tasks:
    - name: Secure state done
      lineinfile: dest=/etc/ANSIBLE_STATE
                  regexp="^secure"
                  line=secure
                  state=present
                  create=yes
