# TODO: better roles in ansible
#
# ANSIBLE_HOSTS=core flock play @@core warewulf --extra-vars='master=core'
#
---
# PTP
- include: roles/warewulf/ptpd.yml

# Warewulf
- include: roles/warewulf/warewulf.yml

# CLI tools
- include: roles/warewulf/tools.yml

# Ansible for the clones
- include: roles/warewulf/ansible.yml

# Slurm stuff
- include: roles/warewulf/slurm.yml

# nfs server for homes
# TODO: lustre ceph and FhGfs
- include: roles/warewulf/nfsserver.yml

# basic node helth check
# TODO
# - include: roles/warewulf/healthcheck.yml

# ganglia procstat
- include: roles/warewulf/procstat.yml

- hosts: all
  tasks:
    - name: Warewulf state done
      lineinfile: dest=/etc/ANSIBLE_STATE
                  regexp="^warewulf"
                  line=warewulf
                  state=present
                  create=yes
      tags:
        - state
