# TODO: better roles in ansible
#
# ANSIBLE_HOSTS=core flock play @@core warewulf --extra-vars='master=core'
#
---
- include: roles/warewulf/warewulf.yml
- include: roles/warewulf/tools.yml

- hosts: all
  tasks:
    - name: Warewulf state done
      lineinfile: dest=/etc/ANSIBLE_STATE
                  regexp="^warewulf"
                  line=warewulf
                  state=present
                  create=yes
      tags:
        - state
