# TODO: from source
---
- hosts: all
  vars_files:
    - vars/modules.yml

  tasks:
### REDHAT
  - name: Download modules
    get_url: url=${url}/${rpm} dest=/root
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install modules
    command: yum -y localinstall /root/${rpm}
    when: ansible_os_family == "RedHat"
    tags:
      - packages

### DEBIAN
  - name: Install modules
    apt: name=environment-modules
         state=installed
    when: ansible_distribution == "Debian"


  - name: Create modulefiles
    file: path=/etc/modulefiles
          state=directory
    tags:
      - config
