# This play modifies
# http://www.ntp.org/ntpfaq/NTP-s-config-adv.htm
#
# --extra-vars "bcast=yes"
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ansible_os_family}}.yml", "vars/Defaults.yml" ]

### FEATURE SWITCHES
  vars:
    is_bcast: "'$bcast' == 'yes'"

  tasks:
    - name: Install NTP Server
      yum: name=ntp
           state=installed
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Install NTP Server
      apt: name=ntp
           state=installed
      when: ansible_os_family == "Debian"
      tags:
        - packages

    - name: Configure NTP Server
      template: src=templates/etc/ntp.conf.j2
                dest=/etc/ntp.conf
                backup=yes
      notify:
        - Restart ntpd
      tags:
        - configs

# TEST: ntpdate
#### CYCLE BEGIN
#    - name: Disable NTP
#      service: name=ntpd
#               state=stopped
#               enabled=no
#      tags:
#        - cycle
#
#    - name: Start NTP early
#      lineinfile: "dest=/etc/init.d/ntpd regexp='^#\ chkconfig' line='# chkconfig: - 25 74' backup=yes"
#      tags:
#        - service
#        - cycle
#
#    - name: Enable NTP
#      service: name=ntpd
#               state=started
#               enabled=yes
#      tags:
#        - cycle
#### CYCLE END

    - name: Set NTP server for ntpdate
      template: src=templates/etc/sysconfig/ntpdate.j2
                dest=/etc/sysconfig/ntpdate
                backup=yes

    - name: Set start options
      lineinfile: dest=/etc/sysconfig/ntpd regexp="^OPTIONS=" line='OPTIONS="-u ntp:ntp -p /var/run/ntpd.pid -g -m"' backup=yes
      notify:
        - Restart ntpd
      tags:
        - configs
        - options

    - name: Stop ntpd
      service: name={{service.ntpd}}
               state=stopped

    - name: Start ntpdate
      service: name=ntpdate
               state=started
               enabled=yes

    - name: Start ntpd
      service: name={{service.ntpd}}
               state=started
               enabled=yes

  handlers:
    - name: Restart ntpd
      service: name={{service.ntpd}}
               state=restarted
