# This play modifies
# http://www.ntp.org/ntpfaq/NTP-s-config-adv.htm
#
# --extra-vars "bcast=yes"
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ansible_os_family}}.yml", "vars/Defaults.yml" ]

### FEATURE SWITCHES
  vars:
    is_bcast: "'$bcast' == 'yes'"

  tasks:
### PACKAGES
    - name: Install NTP Server
      yum: name={{item}}
           state=installed
      with_items:
        - ntp
        - ntpdate
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Install NTP Server
      apt: name={{item}}
           state=installed
      with_items:
        - ntp
        - ntpdate
      when: ansible_os_family == "Debian"
      tags:
        - packages

### CONFIGURATION
    - name: Configure NTP Server
      template: src=templates/etc/ntp.conf.j2
                dest=/etc/ntp.conf
                backup=yes
      notify:
        - Restart ntpd
      tags:
        - config


### NTPDATE
    - name: Set NTP server for ntpdate
      template: src=templates/etc/sysconfig/ntpdate.j2
                dest=/etc/sysconfig/ntpdate
                backup=yes
      when: ansible_os_family == "RedHat"
      tags:
        - config
        - ntpdate

    - name: Set start options
      lineinfile: dest=/etc/sysconfig/ntpd regexp="^OPTIONS=" line='OPTIONS="-u ntp:ntp -p /var/run/ntpd.pid -g -m"' backup=yes
      notify:
        - Restart ntpd
      when: ansible_os_family == "RedHat"
      tags:
        - config


### SERVICES
    - name: Stop ntpd
      service: name={{service.ntpd}}
               state=stopped

    - name: Start ntpdate
      service: name=ntpdate
               state=started
               enabled=yes
      when: ansible_os_family == "RedHat"

    - name: Start ntpd
      service: name={{service.ntpd}}
               state=started
               enabled=yes

  handlers:
    - name: Restart ntpd
      service: name={{service.ntpd}}
               state=restarted
