#
# how to check security updates:
# http://www.cyberciti.biz/faq/redhat-fedora-centos-linux-yum-installs-security-updates/
#
---
- hosts: all

  tasks:

  - name: Install packages
    yum: name={{item}}
         state=installed
    with_items:
      - cronie
      - mc
      - man
      - git
      - gcc
      - gcc-c++
      - make
      - nodejs
      - npm
      - multitail
      - yum-security
      - xorg-x11-xauth
      - libtool
      - curl
      - sqlite-devel
      - sqlite
      - xz
      - pxz
      - unzip
      - xfsprogs
      - createrepo
    when: ansible_os_family == "RedHat"
    tags:
      - packages

  - name: Install preftools
    yum: name={{item}}
         state=installed
    with_items:
      - htop
      - iptraf-ng
      - sysstat
      - nmap
      - mtr
      - perf
      - strace
      - psinfo
      - tcpstat
      - sysstat
      - dstat
      - ifstat
      - iperf
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - perf

# TODO: nodejs and repos
  - name: Install packages
    apt: name={{item}}
         state=installed
    with_items:
      - mc
      - htop
      - iptraf
      - sysstat
      - nmap
      - mtr-tiny
      - manpages
      - git
      - gcc
      - g++
      - python-pip
      - python-crypto
      - python-distutils-extra
      - python-openssl
      - python-dev
      - make
      - multitail
      - rsstail
      - xauth
      - libtool
      - python-software-properties
      - software-properties-common
      - curl
      - miniupnpc
      - sdparm
      - liblzma-dev
    when: ansible_os_family == "Debian"
    tags:
      - packages

  - name: Install basic packages
    apt: name={{item}}
         state=installed
    with_items:
      - sysv-rc-conf
    when: ansible_distribution == "Ubuntu"
    tags:
      - packages
      - ubuntu
