# Enable rpmforge repo
---
- hosts: all
  tasks:
    - group_by: key=${ansible_os_family}
### REDHAT
- hosts: RedHat
  vars_files:
    - vars/rpmforge.yml
  tasks:
    - name: Download rpmforge repo
      get_url: url=${url}/${rpm} dest=/root
      tags:
        - packages

    - name: Install rpmforge repo
      command: yum -y localinstall /root/${rpm}
      tags:
        - packages
