---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]

  tasks:
    - name: Install phpsysinfo
      git: repo=git://github.com/rk4an/phpsysinfo.git
           dest=/opt/phpsysinfo
      tags:
        - packages

    - name: Install /opt/phpsysinfo/phpsysinfo.ini
      copy: src=files/opt/phpsysinfo/phpsysinfo.ini
            dest=/opt/phpsysinfo/phpsysinfo.ini
            owner=root
            group=root
            mode=0644
      tags:
        - config

    - name: Enable phpsysinfo
      template: src=templates/etc/httpd/conf.d/phpsysinfo.conf.j2
                dest=/etc/{{service.httpd}}/conf.d/phpsysinfo.conf
                owner=root
                group=root
                mode=0644
      notify:
        - Restart httpd
      tags:
        - config

  handlers:
    - name: Restart httpd
      service: name={{service.httpd}}
               state=restarted
