#
# syslog-ng based log server
#
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:

  - name: Enable syslog-ng loghost
    template: src=templates/etc/syslog-ng/conf.d/loghost.j2
              dest=/etc/syslog-ng/conf.d/10-loghost.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart syslog-ng
    tags:
      - config

  - name: Enable log compressor
    template: src=templates/etc/cron.daily/compress-syslog.j2
              dest=/etc/cron.daily/compress-syslog
              owner=root
              group=root
              mode=0755
    tags:
      - config
      - compress

### SERVICE
  handlers:
    - name: Restart syslog-ng
      service: name=syslog-ng
               state=restarted
