url: http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo
repo: glusterfs-epel.repo

#
# tune ping and frame timeouts
# vg_pvs: '/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde'

gluster:
  vg_root: 'vg_gluster'
  vg_pvs: '/dev/sdb'
  lv_data: 'lv_glusterfs_common_brick1'
  lv_size: '18000'
  lv_mnt: '/data/glusterfs/common/brick1'
  transport: 'tcp,rdma'
  volume: 'common'
  replica: 3
  common: '/glusterfs/common'
  fio_size: '100M'
  disk: 'sda'
  opts: 'defaults,fetch-attempts=9,_netdev'
  mntopts: 'defaults'
  ping: 30
  frame: 60
