#
# http://nareshv.blogspot.se/2013/08/installing-dockerio-on-centos-64-64-bit.html
#
---
- hosts: all

  tasks:
    - group_by: key=${ansible_os_family}
### REDHAT
- hosts: RedHat
  vars_files:
    - vars/docker.yml
  tasks:
    - name: Download hop5.in repo
      get_url: url=${url}/${repo}
               dest=/etc/yum.repos.d/${repo}
      tags:
        - repo

    - name: Install packages
      yum: name={{item}}
           state=installed
      with_items:
        - docker-io
      tags:
        - packages

    - name: Enable cgroup filesystem
      lineinfile: dest=/etc/fstab
                  regexp='^none /sys/fs/cgroup'
                  line='none /sys/fs/cgroup cgroup defaults 0 0'
                  backup=yes
      tags:
        - fstab
