#
# http://openvpn.net/index.php/open-source/documentation/howto.html#quick
#
# reset ipset:
# --extra-vars "reset=yes"  --tag reset
#
---
- hosts: all

  vars_files:
    - vars/openvpn.yml

  vars:
    is_reset: "'$reset' == 'yes'"

  tasks:
    - name: Install packages
      yum: name={{item}}
           state=installed
      with_items:
        - openvpn
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    - name: Install packages
      apt: name={{item}}
           state=installed
      with_items:
        - openvpn
      when: ansible_os_family == "Debian"
      tags:
        - packages

### CERTIFICATES
    - name: Install /etc/openvpn/ca.crt
      copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/ca.crt
            dest=/etc/openvpn/ca.crt
            owner=root
            group=root
            mode=0644
      tags:
        - ca
        - config

    - name: Install /etc/openvpn/dh2048.pem
      copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/dh2048.pem
            dest=/etc/openvpn/dh2048.pem
            owner=root
            group=root
            mode=0644
      tags:
        - dh
        - config

    - name: Install /etc/openvpn/ta.key
      copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/ta.key
            dest=/etc/openvpn/ta.key
            owner=root
            group=root
            mode=0600
      tags:
        - ta
        - config

    - name: Install /etc/openvpn/server.crt
      copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/{{inventory_hostname}}.crt
            dest=/etc/openvpn/server.crt
            owner=root
            group=root
            mode=0644
      tags:
        - cert
        - config

    - name: Install /etc/openvpn/server.key
      copy: src=ca/{{openvpn.ca}}/{{openvpn.ver}}/keys/{{inventory_hostname}}.key
            dest=/etc/openvpn/server.key
            owner=root
            group=root
            mode=0600
      tags:
        - key
        - config

### FIREWALL
    - name: Install ipset tables
      template: src=templates/etc/ipset.d/{{item}}.j2
                dest=/etc/ipset.d/{{item}}
                owner=root
                group=root
                mode=0755
      with_items:
        - openvpn.sh
      tags:
        - firewall
        - ipset
      notify:
        - Restart ipset

    - name: Reset ipsets
      file: path=/etc/ipset.d/{{item}}
            state=absent
      with_items:
        - openvpn.save
      only_if: '$is_reset'
      notify:
        - Restart ipset
      tags:
        - reset

    - name: Install firewall rules
      template: src=templates/etc/shorewall/rules.d/openvpn.j2
                dest=/etc/shorewall/rules.d/openvpn
                owner=root
                group=root
                mode=0640
      tags:
        - firewall
      notify:
      - Restart shorewall

### CONFIGURATION
    - name: Install ipset tables
      template: src=templates/etc/openvpn/server.conf.j2
                dest=/etc/openvpn/server.conf
                owner=root
                group=root
                mode=0644
      tags:
        - config
      notify:
        - Restart openvpn

    - name: Ubuntu fix
      lineinfile: dest=/etc/openvpn/server.conf
                  regexp='^group'
                  line='group nogroup'
                  backup=yes
      when: ansible_os_family == "Debian"
      tags:
        - config

    - name: Start openvpn
      service: name=openvpn
               state=started
               enabled=yes

### SERVICES
  handlers:
    - name: Restart ipset
      service: name=ipset
               state=reloaded

    - name: Restart shorewall
      service: name=shorewall
               state=restarted

    - name: Restart openvpn
      service: name=openvpn
               state=restarted
