#
# Mind the gap!
#
---
- hosts: all
  connection: chroot
  tasks:

### initial time sync
    - name: Set options
      lineinfile: dest=/etc/sysconfig/ptpd2
                  regexp='^PTPDARGS'
                  line='PTPDARGS="-n Example -D -b eth0 -L -D -i 1 -s 1 -G -w 10000"'
      tags:
        - config
