#
# Mind the gap!
#
---
- hosts: all
  connection: chroot
  tasks:
    - name: Install Yum config
      copy: src=/etc/yum.conf
            dest=/etc/yum.conf
      tags:
        - repo

    - name: Install repositories
      copy: src=/etc/yum.repos.d/$item
            dest=/etc/yum.repos.d/$item
      with_items:
        - elrepo.repo
        - epel.repo
        - home:hornos:centos.repo
        - ganglia.repo
        - rpmforge.repo
        - warewulf-rhel6.repo
      tags:
        - repo

#    - name: Enable vuksan
#      lineinfile: dest=/etc/yum.repos.d/vuksan.repo
#                  regexp='^enabled'
#                  line='enabled=1'
#      tags:
#        - repo
#        - fix
