#!/bin/bash
_hosts=${1:-centos-6}
shift
_opts=${*}

rsync -ar ${_hosts}/* ${_hosts}-upx
pushd ${_hosts}-upx
for i in $(find . -name *.so) ; do upx -qqq --best $i;done
for i in $(find . -executable) ; do upx -qqq --best $i;done
popd
