#
# http://stackoverflow.com/questions/14527311/routing-configuration-to-forward-multicast-traffic-to-a-single-nic-on-redhat-6
#
# TODO: networks.yml
#
---
- hosts: all

  vars_files:
    - networks.yml

  tasks:
    - name: Enable multicast route
      lineinfile: dest=/etc/sysconfig/network-scripts/route-{{interfaces.system}}
                  regexp='^224.0.0.0'
                  line="224.0.0.0/4 dev {{interfaces.system}}"
                  create=yes
      when: ansible_os_family == "RedHat"
      tags:
        - config

# http://guru.kirz.com/?p=129

    - name: Enable multicast route
      lineinfile: dest=/etc/network/interfaces
                  regexp='^up route'
                  line='up route add -net 224.0.0.0/4 dev {{interfaces.system}}'
      when: ansible_os_family == "Debian"
      tags:
        - config
