#
# http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH4/latest/CDH4-Installation-Guide/cdh4ig_topic_12_4.html
#
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/${inventory_hostname}.yml
    - vars/cdh4.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
### REDHAT
  - name: Install packages
    yum: name={{item}}
         state=installed
    with_items:
      - flume-ng
      - flume-ng-agent
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - flume

  - name: Install configuration
    template: src=templates/etc/flume-ng/conf/flume.conf.j2
              dest=/etc/flume-ng/conf/flume.conf
              backup=yes
    tags:
      - config
    notify:
      - Restart flume

  - name: Install syslog forwarder
    template: src=templates/etc/syslog-ng/conf.d/flume.conf.j2
              dest=/etc/syslog-ng/conf.d/30-flume.conf
    tags:
      - config
      - syslog
    notify:
      - Restart syslog

  - name: Start flume
    service: name=flume-ng-agent
             state=started
             enabled=yes

  handlers:
    - name: Restart flume
      service: name=flume-ng-agent
               state=restarted

    - name: Restart syslog
      service: name=syslog-ng
               state=restarted
