#
# http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH4/latest/CDH4-Installation-Guide/cdh4ig_topic_12_4.html
#
# Testing:
# hbase shell
# status 'detailed'
#
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/${inventory_hostname}.yml
    - vars/cdh4.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
### REDHAT
  - name: Install packages
    yum: name={{item}}
         state=installed
    with_items:
      - hue
      - hue-server
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - hue

  - name: Start hue
    service: name=hue
             state=started
             enabled=yes
    when: '$is_master'

### FIREWALL
  - name: Configure firewall
    template: src=templates/etc/shorewall/rules.d/{{item}}.j2
              dest=/etc/shorewall/rules.d/{{item}}
    with_items:
      - hue
    tags:
      - firewall
      - shorewall
    notify:
      - Restart shorewall

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted
