#
# http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH4/latest/CDH4-Installation-Guide/CDH4-Installation-Guide.html
#
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/${inventory_hostname}.yml
    - vars/cdh4.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:

### SERVICES
#  - debug: msg={{master}}

  - name: Enable name services
    service: name={{item}}
             state=started
             enabled=yes
    with_items:
      - hadoop-hdfs-namenode
    when: '$is_master'
    tags:
      - namenode

  - name: Enable data services
    service: name={{item}}
             state=started
             enabled=yes
    with_items:
      - hadoop-hdfs-datanode
    tags:
      - datanode
