#
# Slurm Scheduler
#
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/slurm.yml
    - vars/mariadb.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
  - debug: msg={{master}}
  - debug: msg={{backup}}

  - name: Install packages
    yum: name={{item}}
         state=installed
    with_items:
      - MySQL-python
    tags:
      - packages

  - name: Install slurm packages
    yum: name={{item}}
         state=latest
         enablerepo={{slurm.repo}}
    with_items:
      - slurm
      - slurm-munge
      - slurm-pam_slurm
      - slurm-perlapi
      - slurm-plugins
      - slurm-sjobexit
      - slurm-sjstat
      - slurm-slurmdbd
      - slurm-sql
      - slurm-torque
      - mailx
    tags:
      - packages

  - name: Create users
    user: name={{item}}
          createhome=no
    with_items:
      - slurm
    tags:
      - users

  - name: Setup slurmdbd mysql db
    mysql_db: db={{slurm.db}}
              login_user={{mariadb.user}}
              login_password={{mariadb.password}}
              login_unix_socket={{mariadb.socket}}
    when: '$is_master'
    tags:
      - slurm

  - name: Setup slurmdbd mysql user
    mysql_user: name={{slurm.user}} password={{slurm.password}} priv={{slurm.db}}.*:ALL
                login_user={{mariadb.user}}
                login_password={{mariadb.password}}
                login_unix_socket={{mariadb.socket}}
    when: '$is_master'
    tags:
      - slurm

  - name: Create slurm group
    group: name=slurm
           state=present
    tags:
      - slurm

  - name: Create slurm user
    user: name=slurm
          comment="Slurm Scheduler"
          state=present
          password=*
          group=slurm
    tags:
      - slurm

  - name: Create slurm directories
    file: path=/var/{{item}}/slurm
          owner=slurm
          group=slurm
          state=directory
    with_items:
      - log
      - run
      - lib
    tags:
      - slurm


### DATABASE
  - name: Install /etc/slurm/slurmdbd.conf
    template: src=templates/etc/slurm/slurmdbd.conf.j2
              dest=/etc/slurm/slurmdbd.conf
              owner=slurm
              group=slurm
              mode=0600
              backup=yes
    notify:
      - Restart slurmdbd
    when: '$is_master or $is_backup'
    tags:
      - slurm
      - database

  - name: Install /etc/slurm/slurm.conf
    template: src=templates/etc/slurm/slurm.conf.j2
              dest=/etc/slurm/slurm.conf
              owner=slurm
              group=slurm
              mode=0644
              backup=yes
    notify:
      - Restart slurm
    tags:
      - slurm
      - config
      - slurmctld

### keep the original for slurmconf
  - name: Install /etc/slurm/slurm.conf.template
    template: src=templates/etc/slurm/slurm.conf.template.j2
              dest=/etc/slurm/slurm.conf.template
              owner=slurm
              group=slurm
              mode=0644
    tags:
      - slurm
      - config
      - slurmctld
      - slurmconf

  - name: Start slurmdbd
    service: name=slurmdbd
             state=started
             enabled=yes
    when: '$is_master or $is_backup'
    tags:
      - slurm
      - database

  - name: Create cluster
    shell: /usr/bin/sacctmgr -i create cluster name={{slurm.cluster}}
    when: '$is_master'
    ignore_errors: yes
    tags:
      - slurm

  - name: Create test account
    shell: /usr/bin/sacctmgr -i add account sysop
    when: '$is_master'
    ignore_errors: yes
    tags:
      - slurm

  - name: Enable test account
    shell: /usr/bin/sacctmgr -i add user sysop defaultaccount=sysop
    when: '$is_master'
    ignore_errors: yes
    tags:
      - slurm


  - name: Create state directory
    file: path={{slurm.state}}
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    when: '$is_master'
    tags:
      - slurm

  - name: Create checkpoint directory
    file: path={{slurm.checkpoint}}
          owner=slurm
          group=slurm
          state=directory
    tags:
      - state
    when: '$is_master'
    tags:
      - slurm

  - name: Create spool directory
    file: path=/var/spool/slurmd
          owner=slurm
          group=slurm
          state=directory
    tags:
      - slurm

  - name: Install /etc/sysconfig/slurm
    template: src=templates/etc/sysconfig/slurm.j2
              dest=/etc/sysconfig/slurm
              owner=slurm
              group=slurm
              mode=0644
    notify:
      - Restart slurm
    tags:
      - slurm

  - name: Install logrotate
    template: src=templates/etc/logrotate.d/slurm.j2
              dest=/etc/logrotate.d/slurm
              owner=slurm
              group=slurm
              mode=0644
    tags:
      - slurm

  - name: Enable slurmctld service
    lineinfile: dest=/etc/services
                regexp="^slurmctld 6817/{{item}}"
                line="slurmctld 6817/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable slurmd service
    lineinfile: dest=/etc/services
                regexp="^slurmd 6818/{{item}}"
                line="slurmd 6818/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable slurmdbd service
    lineinfile: dest=/etc/services
                regexp="^slurmdbd 6819/{{item}}"
                line="slurmdbd 6819/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

### IPSet
  - name: Install ipset tables
    template: src=templates/etc/ipset.d/{{item}}.j2
              dest=/etc/ipset.d/{{item}}
              owner=root
              group=root
              mode=0755
    with_items:
      - compute.sh
    tags:
      - firewall
      - ipset
    notify:
      - Restart ipset

### Firewall
  - name: Install firewall rules
    template: src=templates/etc/shorewall/rules.d/slurm.j2
              dest=/etc/shorewall/rules.d/slurm
              owner=root
              group=root
              mode=0640
    tags:
      - firewall
    notify:
      - Restart shorewall


  - name: Start slurm
    service: name=slurm
             state=started
             enabled=yes

  handlers:
    - name: Restart slurmdbd
      service: name=slurmdbd
               state=restarted

    - name: Restart slurm
      service: name=slurm
               state=restarted

    - name: Restart ipset
      service: name=ipset
               state=reloaded

    - name: Restart shorewall
      service: name=shorewall
               state=restarted
