---
- hosts: all

  vars_files:
    - networks.yml
    - vars/warewulf.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
    - name: Install packages
      yum: name={{item}}
           state=installed
      with_items:
        - PyYAML
        - python-paramiko
        - python-jinja2
        - ansible
      tags:
        - packages

### INVENTORY
    - name: Install clone inventory
      template: src=templates/chroots/hosts.j2
                dest={{warewulf.common}}/chroots/hosts
      tags:
        - clone
        - inventory

### DIRECTORIES
    - name: Create directories
      file: path={{warewulf.common}}/chroots/{{item}}
            state=directory
      with_items:
        - playbooks
        - playbooks/templates
        - playbooks/keys
      tags:
        - clone
        - directories

### PLAYBOOKS
    # lightweight clone playbooks
    - name: Install clone playbooks
      copy: src=templates/chroots/playbooks/{{item}}
            dest={{warewulf.common}}/chroots/playbooks/{{item}}
      with_items:
        - repos.yml
        - rsyslog.yml
        - ganglia.yml
        - users.yml
        - munge.yml
        - slurm.yml
      tags:
        - clone
        - playbooks

### SCRIPTS
    - name: Install clone scripts
      copy: src=templates/chroots/{{item}}
            dest={{warewulf.common}}/chroots/{{item}}
            owner=root
            group=root
            mode=0755
      with_items:
        - clonebook
        - cloneyum
        - clonepackages
        - cloneimage
        - cloneupx
        - clonekernel
      tags:
        - clone
        - scripts

### TEMPLATES
    - name: Install clone templates
      copy: src=templates/chroots/playbooks/templates/{{item}}
            dest={{warewulf.common}}/chroots/playbooks/templates/{{item}}
      with_items:
        - rsyslog.conf
        - gmond.conf
        - route-eth0
      tags:
        - clone
        - templates
