---
- hosts: all

  vars_files:
    - networks.yml
    - vars/warewulf.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:
    - name: Install packages
      yum: name={{item}}
           state=installed
      with_items:
        - nfs4-acl-tools
        - nfs-utils
        - nfswatch
        - rpcbind
      tags:
        - packages

### DIRECTORIES
    - name: Create scratch directory
      file: path={{warewulf.scratch}}
            state=directory
      tags:
        - scratch
        - directories
      when: '$is_master'

    - name: Create home directory
      file: path={{warewulf.home}}
            state=directory
      tags:
        - home
        - directories
      when: '$is_master'

    - name: Create software directory
      file: path={{warewulf.software}}
            state=directory
      tags:
        - home
        - directories
      when: '$is_master'

### CONFIGURATION
    - name: Install /etc/syconfig/nfs
      template: src=templates/etc/sysconfig/nfs.j2
                dest=/etc/sysconfig/nfs
                backup=yes
      tags:
        - config

### EXPORTS
    - name: Install /etc/exports
      template: src=templates/etc/exports.j2
                dest=/etc/exports
                backup=yes
      notify:
        - Reload nfs
      tags:
        - exports

### FIREWALL
    - name: Install firewall rules
      template: src=templates/etc/shorewall/rules.d/nfsserver.j2
                dest=/etc/shorewall/rules.d/nfsserver
                owner=root
                group=root
                mode=0640
      tags:
        - firewall
      notify:
        - Restart shorewall

### SERVICES
    - name: Start rpcbind
      service: name=rpcbind
               state=started
               enabled=yes

    - name: Start nfs
      service: name=nfs
               state=started
               enabled=yes

    - name: Start nfslock
      service: name=nfslock
               state=started
               enabled=yes

  handlers:
    - name: Restart shorewall
      service: name=shorewall
               state=restarted

    - name: Reload nfs
      service: name=nfs
               state=reloaded
