
---
- hosts: all
  vars_files:
    - vars/warewulf.yml

  tasks:
    - name: Create {{warewulf.common}}/bin
      file: path={{warewulf.common}}/bin
            state=directory

    - name: Install warewulf tools
      template: src=templates/root/bin/{{item}}.j2
                dest={{warewulf.common}}/bin/{{item}}
                owner=root
                group=root
                mode=0755
      with_items:
        - wwyum
        - wwservice
