
---
- hosts: all
  vars_files:
    - vars/warewulf.yml

  vars:
    target: 'sl-6'

  tasks:
    - name: Create image {{target}}
      shell: "yes | wwvnfs --chroot {{warewulf.common}}/chroots/{{target}}"
      tags:
        - image
        - target
