---
erlang:
  url: http://binaries.erlang-solutions.com/rpm/centos
  repo: erlang_solutions.repo
  key: http://binaries.erlang-solutions.com/debian/erlang_solutions.asc

url: http://www.rabbitmq.com/releases/rabbitmq-server/v3.1.3
rpm: rabbitmq-server-3.1.3-1.noarch.rpm
key: http://www.rabbitmq.com/rabbitmq-signing-key-public.asc

rabbitmq:
  user: 'root'
  password: 'root'
