#
# Install Mainline Kernel
#
---
- hosts: all

  tasks:

### REDHAT
  - name: Update packages
    shell: yum -y --exclude=kernel* update
    when: ansible_os_family == "RedHat"
    tags:
      - packages
