#
# Ganglia cluster monitor
#
# http://vuksan.com/centos/RPMS/x86_64/
#
# rollback:
# --extra-vars "rollback=yes"
#
# latest version repo bug
# http://vuksan.com/centos/RPMS-6/x86_64/ganglia-devel-3.6.0-1.x86_64.rpm
# http://vuksan.com/centos/RPMS-6/x86_64/ganglia-gmetad-3.6.0-1.x86_64.rpm
# http://vuksan.com/centos/RPMS-6/x86_64/ganglia-gmond-3.6.0-1.x86_64.rpm
# http://vuksan.com/centos/RPMS-6/x86_64/ganglia-gmond-modules-python-3.6.0-1.x86_64.rpm
# http://vuksan.com/centos/RPMS-6/x86_64/libganglia-3.6.0-1.x86_64.rpm
#
# TODO: gmetad rrd ntpd update problem
# TODO: ganglia-web
#
# local repo: http://www.unix.com/unix-advanced-expert-users/187517-how-install-rpm-file-directory-using-yum.html
#
---
- hosts: all

  vars_files:
    - networks.yml
    - [ "vars/{{ ansible_os_family }}.yml", "vars/Defaults.yml" ]
    - vars/ganglia.yml

  vars:
    is_rollback: "'$rollback' == 'yes'"

  tasks:
### REDHAT
  - name: Install repo fix script
    template: src=templates/root/ganglia_local_repo.j2
              dest=/root/ganglia_local_repo
              mode=0750
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - fix

  - name: Run fix script
    shell: /root/ganglia_local_repo
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - fix

  - name: Install local Ganglia repo
    template: src=templates/etc/yum.repos.d/ganglia.repo.j2
              dest=/etc/yum.repos.d/ganglia.repo
    tags:
      - packages
      - fix

  - name: Install packages
    yum: name={{item}}
         state=latest
    with_items:
      - ganglia-devel
      - ganglia-gmetad
      - ganglia-gmond
      - ganglia-gmond-modules-python
      - libganglia
    tags:
      - packages

# TODO: from rpm
### Ganglia web
  - name: Install ganglia-web
    git: repo=https://github.com/ganglia/ganglia-web.git
         dest=/var/www/html/ganglia
    when: ansible_os_family == "RedHat"
    tags:
      - packages
      - web

### DEBIAN
  # sudo add-apt-repository ppa:rufustfirefly/ganglia
  #
  # flock play @@core roles/monitor/ganglia --extra-vars="ganglia.version=3.4.0"
  #
  - name: Install repository
    apt_repository: repo=ppa:rufustfirefly/ganglia
    when: ansible_os_family == "Debian"
    tags:
      - packages
      - repo

  - name: F**k Ubuntu shit fix again 1
    file: path=/usr/share/ganglia-webfrontend/lib/{{item}}
          owner=root
          group=www-data
          state=directory
    with_items:
      - dwoo/cache
      - dwoo/compiled
    when: ansible_os_family == "Debian"
    tags:
      - shit
      - fix

  - name: F**k Ubuntu shit fix again 2
    file: path=/var/lib/ganglia-web/{{item}}
          owner=root
          group=www-data
          mode=0775
          state=directory
    with_items:
      - dwoo/cache
      - dwoo/compiled
    when: ansible_os_family == "Debian"
    tags:
      - shit
      - fix

  - name: Install packages
    apt: name={{item}}
         state=latest
    with_items:
      - ganglia-monitor
      - ganglia-webfrontend
      - gmetad
    when: ansible_os_family == "Debian"
    tags:
      - packages

### CONFIGURATION
  - name: Ganglia monitor
    template: src=templates/etc/ganglia/{{ganglia.version}}/gmond.conf.j2
              dest=/etc/ganglia/gmond.conf
              owner=root
              group=root
              mode=0644
              backup=yes
    notify:
      - Restart gmond
    tags:
      - config

  - name: Ganglia metadata
    template: src=templates/etc/ganglia/{{ganglia.version}}/gmetad.conf.j2
              dest=/etc/ganglia/gmetad.conf
              owner=root
              group=root
              mode=0644
              backup=yes
    notify:
      - Restart gmetad
    tags:
      - config

### DEBIAN
  - name: Ganglia monitor
    template: src=templates/etc/ganglia/3.4.0/{{ansible_os_family}}/gmond.conf.j2
              dest=/etc/ganglia/gmond.conf
              owner=root
              group=root
              mode=0644
              backup=yes
    when: ansible_os_family == "Debian"
    notify:
      - Restart gmond
    tags:
      - config

  - name: Ganglia metadata
    template: src=templates/etc/ganglia/3.4.0/{{ansible_os_family}}/gmetad.conf.j2
              dest=/etc/ganglia/gmetad.conf
              owner=root
              group=root
              mode=0644
              backup=yes
    when: ansible_os_family == "Debian"
    notify:
      - Restart gmetad
    tags:
      - config

### FIX
  - name: Disable netstats
    file: path=/etc/ganglia/conf.d/netstats.pyconf
          state=absent
          backup=yes
    tags:
      - fix
      - netstats
    notify:
      - Restart gmond


  - name: Set rrds mode
    file: path=/var/lib/ganglia/rrds/
          state=directory
          recurse=yes
          owner=nobody
          group=nobody
    when: ansible_os_family == "RedHat"
    tags:
      - perm

  - name: Set rrds mode
    file: path=/var/lib/ganglia/rrds/
          state=directory
          recurse=yes
          owner=nobody
          group=nogroup
    when: ansible_os_family == "Debian"
    tags:
      - perm

  # TODO: optional home network
  - name: Enable Ganglia web interface
    template: src=templates/etc/httpd/conf.d/ganglia.conf.j2
              dest=/etc/{{service.httpd}}/conf.d/ganglia.conf
              owner=root
              group=root
              mode=0644
    notify:
      - Restart httpd
    tags:
      - config

  - name: Enable topcoat style
    lineinfile: dest=/var/www/html/ganglia/styles.css
                regexp='^@import'
                line='@import url("/topcoat/css/topcoat-desktop-light.min.css");'
                backup=yes
    when: ansible_os_family == "RedHat"
    tags:
      - frontend
      - topcoat

# TODO: web interface configuration
  - name: Create dwoo directories
    file: path=/var/lib/ganglia/{{item}}
          state=directory
          owner=apache
    with_items:
      - dwoo/cache
      - dwoo/compiled
      - conf
    when: ansible_os_family == "RedHat"
    tags:
      - config
      - gweb

  - name: Install gweb config
    template: src=templates/var/www/html/ganglia/conf_default.php.j2
              dest=/var/www/html/ganglia/conf_default.php
              backup=yes
    when: ansible_os_family == "RedHat"
    tags:
      - config
      - gweb

  - name: Enable gmond service
    lineinfile: dest=/etc/services
                regexp="^gmond 8649/{{item}}"
                line="gmond 8649/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-xml service
    lineinfile: dest=/etc/services
                regexp="^gmetad-xml 8651/{{item}}"
                line="gmetad-xml 8651/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

  - name: Enable gmetad-int service
    lineinfile: dest=/etc/services
                regexp="^gmetad-int 8652/{{item}}"
                line="gmetad-int 8652/{{item}}"
    with_items:
     - tcp
     - udp
    tags:
      - config
      - services

### FIREWALL
# TODO: nosys
  - name: Install firewall rules
    template: src=templates/etc/shorewall/rules.d/ganglia.j2
              dest=/etc/shorewall/rules.d/ganglia
              owner=root
              group=root
              mode=0640
    tags:
      - firewall
    notify:
      - Restart shorewall

  - name: Start gmond
    service: name={{service.gmond}}
             state=started
             enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Stop gmond
    service: name={{service.gmond}}
             state=stopped
             enabled=no
    ignore_errors: yes
    when: ansible_os_family == "Debian"

### rearrange service order
  - name: Stop gmetad
    service: name=gmetad
             state=stopped
             enabled=no
    when: ansible_os_family == "RedHat"
    tags:
      - gmetad

  - name: Gmetad should start after ntpd
    lineinfile: "dest=/etc/init.d/gmetad regexp='^#\ chkconfig' line='# chkconfig: 2345 65 80' backup=yes"
    when: ansible_os_family == "RedHat"
    tags:
      - service
      - gmetad

  - name: Start gmetad
    service: name=gmetad
             state=started
             enabled=yes
    when: ansible_os_family == "RedHat"
    tags:
      - gmetad

# TODO
  - name: Stop gmetad
    service: name=gmetad
             state=stopped
             enabled=no
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    tags:
      - gmetad


  - name: Start httpd
    service: name={{service.httpd}}
             state=started
             enabled=yes

  handlers:
    - name: Restart gmond
      when: ansible_os_family == "RedHat"
      service: name={{service.gmond}}
               state=restarted

    - name: Restart gmetad
      when: ansible_os_family == "RedHat"
      service: name=gmetad
               state=restarted


    - name: Restart shorewall
      service: name=shorewall
               state=restarted

    - name: Restart httpd
      service: name={{service.httpd}}
               state=restarted
