#
# http://crankysysadmin.com/secure-logstash-install/
#
---
- hosts: all

  vars_files:
    - vars/logstash.yml

  tasks:
### REDHAT
    - name: Install packages
      yum: name={{item}}
           state=installed
      when: ansible_os_family == "RedHat"
      with_items:
        - java-1.7.0-openjdk
      tags:
        - packages

### DEBIAN
    - name: Install packages
      apt: name={{item}}
           state=installed
      when: ansible_os_family == "Debian"
      with_items:
        - openjdk-7-jre-headless
      tags:
        - packages

### DIRECTORIES
    - name: Create /opt/logstash
      file: path=/opt/logstash
            state=directory
      tags:
        - directories

    - name: Download logstash
      get_url: url={{url}}/{{jar}} dest=/opt/logstash/{{jar}}
      tags:
        - packages

    - name: Create logstash user
      user: name=logstash
            state=present
      tags:
        - users

    - name: Create directories
      file: path={{item}}
            state=directory
            owner=root
            group=logstash
            mode=0755
      with_items:
        - /var/run/logstash
        - /var/lib/logstash
        - /var/lib/logstash/data

### CONFIGURATION
    - name: Install configuration
      template: src=templates/etc/logstash.conf.j2
                dest=/etc/logstash.conf
      tags:
        - config

#    - name: Install sevice

### FIREWALL
# TCP 9200-9400

#### SERVICES
#    - name: Enable elasticsearch
#      service: name=elasticsearch
#               state=started
#               enabled=yes
#
#  handlers:
#    - name: Restart elasticsearch
#      service: name=elasticsearch
#               state=restarted
