# Warewulf Cluster
# http://www.admin-magazine.com/HPC/Articles/Warewulf-Cluster-Manager-Master-and-Compute-Nodes
# http://www.admin-magazine.com/HPC/Articles/Warewulf-Cluster-Manager-Completing-the-Environment
#
# TODO: consider /usr/bin/cluster-env for regular users
#
# better rsyslog
# ldap inetgration
# slurm integration
# storage integration
#
# flock play @@core roles/warewulf/datastore.yml --extra-vars='master=core'
#
---
- hosts: all
  vars_files:
    - networks.yml
    - vars/mariadb.yml
    - vars/warewulf.yml

  vars:
    is_master: "'$inventory_hostname' == '$master'"
    is_backup: "'$inventory_hostname' == '$backup'"

  tasks:

  # TODO: skip
  - name: Create sl-6 directories
    file: 'path={{warewulf.common}}/datastore/sl-6/etc owner=root group=root state=directory'
    tags:
      - directories
    when: '$is_master'

   # mind that datastore is not absolute
  - name: Install rsyslog compute config
    template: src=templates/datastore/sl-6/etc/rsyslog.conf.j2
              dest={{warewulf.common}}/datastore/sl-6/etc/rsyslog.conf
    tags:
      - syslog
    when: '$is_master'

  - name: Install scripts
    template: src=templates/root/{{item}}.j2
              dest=/root/{{item}}
              mode=0755
              owner=root
              group=root
    with_items:
      - package_ganglia
    tags:
      - scripts
