#
# Slurm
#
slurm:
  cluster: ww
  user: 'slurm'
  password: 'slurm'
  db: 'slurm_acct_db'
  repo: 'home_hornos_centos'
  state: '/common/slurm/state'
  checkpoint: '/common/slurm/checkpoint'
  compute: 'ww-[01-3]'
  timeout: 60
