# This play secures the server
# Based on RH EAL4+ recommenadtions
---
- include: entropy.yml
- include: login_defs.yml
- include: su.yml
- include: sudo.yml
- include: ssh_server.yml
- include: selinux.yml

- hosts: all
  tasks:
    - name: Secure role
      lineinfile: dest=/etc/ANSIBLE_ROLE
                  regexp="^secure"
                  line=secure
                  state=present
                  create=yes
      tags:
        - role
