# This play secures su
---
- hosts: all

  tasks:
    - name: Secure su
      lineinfile: dest=/etc/pam.d/su
                  state=present
                  regexp="^auth.*required.*pam_wheel.so.*use_uid"
                  insertbefore="^auth.*include"
                  line="auth required pam_wheel.so use_uid"
                  backup=yes
      when: ansible_os_family == "RedHat"
      tags:
        - config

    - name: Secure su
      lineinfile: dest=/etc/pam.d/su
                  state=present
                  regexp="^auth.*required.*pam_wheel.so"
                  insertbefore="^# auth.*required.*pam_wheel.so"
                  line="auth required pam_wheel.so group=sudo use_uid"
                  backup=yes
      when: ansible_os_family == "Debian"
      tags:
        - config
