#
# Clean up for a template image
#
---
- hosts: all

  tasks:

### REDHAT
  - name: Clean /etc/hosts
    lineinfile: dest=/etc/hosts
                regexp='{{inventory_hostname}}'
                state=absent
    tags:
      - hosts

  - name: Reset eth0
    template: src=templates/etc/sysconfig/network-scripts/ifcfg-eth0.j2
              dest=/etc/sysconfig/network-scripts/ifcfg-eth0
    tags:
      - interfaces

  - name: Reset eth1
    template: src=templates/etc/sysconfig/network-scripts/ifcfg-eth1.j2
              dest=/etc/sysconfig/network-scripts/ifcfg-eth1
    tags:
      - interfaces

  - name: Clear persistent rules
    file: path=/etc/udev/rules.d/70-persistent-net.rules
          state=absent
    tags:
      - udev
